

import Zapato from './image/Black-Converse.png'

const Information = [
    {   id: 108,
        image: Zapato,
        name: 'Sandalia negra',
        description: 'Modelo de dama',
        category: 'mujer',
        price: '8000',
        stock: 15,
        init: 1,
    },
    {   id: 109,
        image: Zapato,
        name: 'Zapatilla Runner',
        description: 'Modelo de dama',
        category: 'mujer',
        price: '8500',
        stock: 5,
        init: 1,
    },
    {   id: 342,
        image: Zapato,
        name: 'Zapatillas Star',
        description: '',
        category: 'niños',
        price: '20000',
        stock: 2,
        init: 1,
    },
    {   id: 343,
        image: Zapato,
        name: 'Zapatillas Star rosados',
        description: '',
        category: 'niños',
        price: '18000',
        stock: 8,
        init: 1,
    },
    {   id: 119,
        image: Zapato,
        name: 'Zapato casual azul',
        description: '',
        category: 'hombre',
        price: '12000',
        stock: 3,
        init: 1,
    },
    {   id: 120,
        image: Zapato,
        name: 'Zapato casual gris',
        description: '',
        category: 'hombre',
        price: '9500',
        stock: 30,
        init: 1,
    },
    {   id: 246,
        image: Zapato,
        name: 'Zapatillas Taylor',
        description: '',
        category: 'deportes',
        price: '7000',
        stock: 4,
        init: 1,
    },
    {   id: 247,
        image: Zapato,
        name: 'Runner confort',
        description: '',
        category: 'deportes',
        price: '5000',
        stock: 4,
        init: 1,
    }
]


export {
    Information    
}